name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install vsce
      run: npm install -g vsce
    
    - name: Compile TypeScript
      run: npm run compile
    
    - name: Package extension
      run: vsce package
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## What's Changed
          
          ### Features
          - Carbon Design System spacing token suggestions
          - Hardcoded value detection and replacement
          - Performance optimizations for SCSS files
          - Smart import detection with multiple quote styles
          
          ### Installation
          1. Download the `.vsix` file from this release
          2. In VS Code, go to Extensions (Ctrl+Shift+X)
          3. Click the "..." menu and select "Install from VSIX..."
          4. Choose the downloaded file
          
          ### Usage
          - Type `$` after spacing properties to see Carbon token suggestions
          - Use quick fixes to replace hardcoded values
          - Use "Fix All" command to replace all hardcoded values at once
        draft: false
        prerelease: false
    
    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./vscode-carbonmate-*.vsix
        asset_name: carbonmate.vsix
        asset_content_type: application/octet-stream 